export const SET_EXPENSES = 'SET_EXPENSES';
export const SET_EXPENSES_SUCCESS = 'SET_EXPENSES_SUCCESS';
export const SET_EXPENSES_FAILED = 'SET_EXPENSES_FAILED';

export const GET_EXPENSES = 'GET_EXPENSES';
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS';
export const GET_EXPENSES_FAILED = 'GET_EXPENSES_FAILED';