export const SET_INCOMES = 'SET_INCOMES';
export const SET_INCOMES_SUCCESS = 'SET_INCOMES_SUCCESS';
export const SET_INCOMES_FAILED = 'SET_INCOMES_FAILED';

export const GET_INCOMES = 'GET_INCOMES';
export const GET_INCOMES_SUCCESS = 'GET_INCOMES_SUCCESS';
export const GET_INCOMES_FAILED = 'GET_INCOMES_FAILED';